export const TEST_COMMUNICATION = "TEST_COMMUNICATION";
export const GET_COIN_RANKING = "GET_COIN_RANKING";
export const GET_COIN_PRICE_HISTORY = "GET_COIN_PRICE_HISTORY";
export const GET_TWEET = "GET TWEET";
